# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](https://github.com/mahmoodasayeedi/lab-neural-networks/blob/master/your-code/tttboard.jpg?raw=1)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

In [54]:
!git clone https://github.com/mahmoodasayeedi/lab-neural-networks.git

fatal: destination path 'lab-neural-networks' already exists and is not an empty directory.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [55]:
#Load the dataset
import pandas as pd

df = pd.read_csv('/content/lab-neural-networks/your-code/tic-tac-toe.csv')

df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [56]:
#EDA
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

In [57]:
# Check for missing values to determine reliability
print("\nMissing values per column:")
print(df.isnull().sum())

Missing values per column:
TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [58]:
#summarize
df.describe()

         TL   TM   TR   ML   MM   MR   BL   BM   BR class
count   958  958  958  958  958  958  958  958  958   958
unique    3    3    3    3    3    3    3    3    3     2
top       x    x    x    x    x    x    x    x    x  True
freq    418  378  418  378  458  378  418  378  418   626

In [59]:
# Separate features (X) and label/target (y)
X = df.iloc[:, :-1].copy()  # Selection of all columns except the last one
y_raw= df.iloc[:, -1].copy()   # Selection of only the last column

print(f"Inputs shape: {X.shape}, Output shape: {y_raw.shape}")

Inputs shape: (958, 9), Output shape: (958,)

In [60]:
#1. Convert the categorical values to numeric in all columns.
from sklearn.preprocessing import LabelEncoder

# Clean up any accidental whitespaces and force lowercase
for col in X.columns:
    X[col] = X[col].astype(str).str.strip().str.lower()

# 3. Clean Feature Mapping (Neutralizes label ordering conflict)
# This maps blank spaces to 0, 'o' to -1, and 'x' to 1
mapping = {'b': 0, 'o': -1, 'x': 1}
for col in X.columns:
    X[col] = X[col].map(mapping)

# Double-check: If anything failed to map, fill it safely with 0
X = X.fillna(0)


# 4. Encode the target column safely (positive -> 1, negative -> 0)
le = LabelEncoder()
y = le.fit_transform(y_raw.astype(str).str.strip().str.lower())

# View data after transformation
print(df.head())

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [61]:
from sklearn.preprocessing import MinMaxScaler

# 4.Initialize the MinMaxScaler
scaler = MinMaxScaler()

# 5. Normalize features using MinMaxScaler to a clean 0 to 1 scale
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [62]:
# 1. Split the training and test data.
from sklearn.model_selection import train_test_split

# Split into 80% training and 20% test data
X_train, X_test, y_train, y_test = train_test_split(
    X_normalized, y, test_size=0.2, random_state=42
)

In [63]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Initialize the Sequential model
model = Sequential()

# Input layer + first middle (hidden) layer with ReLU
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))

# Additional middle (hidden) layer with ReLU
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
# Output layer with Softmax (assumes 2 unique class labels for the outcome)
model.add(Dense(2, activation='softmax'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [64]:
# Compile with a standard stable learning rate
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.002),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [65]:
# Train the model
history = model.fit(
    X_train,
    y_train,
    epochs=120,
    batch_size=16,
    validation_split=0.1,
    verbose=1
)

Epoch 1/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.7141 - loss: 0.5641 - val_accuracy: 0.7532 - val_loss: 0.4890
Epoch 2/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7721 - loss: 0.4878 - val_accuracy: 0.8182 - val_loss: 0.4344
Epoch 3/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8491 - loss: 0.3743 - val_accuracy: 0.8442 - val_loss: 0.3315
Epoch 4/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9115 - loss: 0.2539 - val_accuracy: 0.9351 - val_loss: 0.2465
Epoch 5/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9768 - loss: 0.1338 - val_accuracy: 0.9870 - val_loss: 0.1271
Epoch 6/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9855 - loss: 0.0781 - val_accuracy: 0.9221 - val_loss: 0.1947
Epoch 7/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9768 - loss: 0.0627 - val_accuracy: 0.9610 - val_loss: 0.1072
Epoch 8/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9956 - loss: 0.0286 - val_accuracy: 0.9870 - val_loss: 0.0618
Epoch 9/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0133 - val_accuracy: 0.9870 - val_loss: 0.0595
Epoch 10/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0070 - val_accuracy: 0.9870 - val_loss: 0.0577
Epoch 11/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.9870 - val_loss: 0.0534
Epoch 12/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.9870 - val_loss: 0.0555
Epoch 13/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.9870 - val_loss: 0.0566
Epoch 14/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.9870 - val_loss: 0.0549
Epoch 15/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9870 - val_loss: 0.0607
Epoch 16/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.9870 - val_loss: 0.0576
Epoch 17/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9870 - val_loss: 0.0607
Epoch 18/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.6762e-04 - val_accuracy: 0.9870 - val_loss: 0.0630
Epoch 19/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.7028e-04 - val_accuracy: 0.9870 - val_loss: 0.0556
Epoch 20/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.4996e-04 - val_accuracy: 0.9870 - val_loss: 0.0627
Epoch 21/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 6.4891e-04 - val_accuracy: 0.9870 - val_loss: 0.0635
Epoch 22/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.8463e-04 - val_accuracy: 0.9870 - val_loss: 0.0606
Epoch 23/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.2293e-04 - val_accuracy: 0.9870 - val_loss: 0.0622
Epoch 24/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.8548e-04 - val_accuracy: 0.9870 - val_loss: 0.0623
Epoch 25/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.2935e-04 - val_accuracy: 0.9870 - val_loss: 0.0614
Epoch 26/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.8893e-04 - val_accuracy: 0.9870 - val_loss: 0.0610
Epoch 27/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.5061e-04 - val_accuracy: 0.9870 - val_loss: 0.0615
Epoch 28/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.1822e-04 - val_accuracy: 0.9870 - val_loss: 0.0633
Epoch 29/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.9025e-04 - val_accuracy: 0.9870 - val_loss: 0.0618
Epoch 30/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.7026e-04 - val_accuracy: 0.9870 - val_loss: 0.0650
Epoch 31/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.4862e-04 - val_accuracy: 0.9870 - val_loss: 0.0660
Epoch 32/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.2749e-04 - val_accuracy: 0.9870 - val_loss: 0.0650
Epoch 33/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.1367e-04 - val_accuracy: 0.9870 - val_loss: 0.0671
Epoch 34/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.9923e-04 - val_accuracy: 0.9870 - val_loss: 0.0672
Epoch 35/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.8247e-04 - val_accuracy: 0.9870 - val_loss: 0.0690
Epoch 36/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.6967e-04 - val_accuracy: 0.9870 - val_loss: 0.0666
Epoch 37/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.5942e-04 - val_accuracy: 0.9870 - val_loss: 0.0672
Epoch 38/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.4775e-04 - val_accuracy: 0.9870 - val_loss: 0.0678
Epoch 39/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.3974e-04 - val_accuracy: 0.9870 - val_loss: 0.0660
Epoch 40/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.3785e-04 - val_accuracy: 0.9870 - val_loss: 0.0748
Epoch 41/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.2833e-04 - val_accuracy: 0.9870 - val_loss: 0.0703
Epoch 42/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.1614e-04 - val_accuracy: 0.9870 - val_loss: 0.0717
Epoch 43/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.0981e-04 - val_accuracy: 0.9870 - val_loss: 0.0689
Epoch 44/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.0182e-04 - val_accuracy: 0.9870 - val_loss: 0.0683
Epoch 45/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.6076e-05 - val_accuracy: 0.9870 - val_loss: 0.0696
Epoch 46/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.0205e-05 - val_accuracy: 0.9870 - val_loss: 0.0693
Epoch 47/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.5927e-05 - val_accuracy: 0.9870 - val_loss: 0.0697
Epoch 48/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.2308e-05 - val_accuracy: 0.9870 - val_loss: 0.0707
Epoch 49/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.7290e-05 - val_accuracy: 0.9870 - val_loss: 0.0694
Epoch 50/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.4375e-05 - val_accuracy: 0.9870 - val_loss: 0.0691
Epoch 51/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 6.9183e-05 - val_accuracy: 0.9870 - val_loss: 0.0717
Epoch 52/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 6.5704e-05 - val_accuracy: 0.9870 - val_loss: 0.0711
Epoch 53/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 6.2541e-05 - val_accuracy: 0.9870 - val_loss: 0.0687
Epoch 54/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.9389e-05 - val_accuracy: 0.9870 - val_loss: 0.0707
Epoch 55/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.6174e-05 - val_accuracy: 0.9870 - val_loss: 0.0710
Epoch 56/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.3618e-05 - val_accuracy: 0.9870 - val_loss: 0.0702
Epoch 57/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.1839e-05 - val_accuracy: 0.9870 - val_loss: 0.0735
Epoch 58/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 1.0000 - loss: 4.8576e-05 - val_accuracy: 0.9870 - val_loss: 0.0725
Epoch 59/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.7005e-05 - val_accuracy: 0.9870 - val_loss: 0.0706
Epoch 60/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 5.2136e-05 - val_accuracy: 0.9870 - val_loss: 0.0692
Epoch 61/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.4301e-05 - val_accuracy: 0.9870 - val_loss: 0.0685
Epoch 62/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.1697e-05 - val_accuracy: 0.9870 - val_loss: 0.0681
Epoch 63/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.4781e-05 - val_accuracy: 0.9870 - val_loss: 0.0747
Epoch 64/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.7482e-05 - val_accuracy: 0.9870 - val_loss: 0.0712
Epoch 65/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.4528e-05 - val_accuracy: 0.9870 - val_loss: 0.0711
Epoch 66/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.2909e-05 - val_accuracy: 0.9870 - val_loss: 0.0733
Epoch 67/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.1228e-05 - val_accuracy: 0.9870 - val_loss: 0.0719
Epoch 68/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.0102e-05 - val_accuracy: 0.9870 - val_loss: 0.0754
Epoch 69/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.1700e-05 - val_accuracy: 0.9870 - val_loss: 0.0749
Epoch 70/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.7998e-05 - val_accuracy: 0.9870 - val_loss: 0.0733
Epoch 71/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.6461e-05 - val_accuracy: 0.9870 - val_loss: 0.0741
Epoch 72/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.5596e-05 - val_accuracy: 0.9870 - val_loss: 0.0764
Epoch 73/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.4640e-05 - val_accuracy: 0.9870 - val_loss: 0.0753
Epoch 74/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.3691e-05 - val_accuracy: 0.9870 - val_loss: 0.0756
Epoch 75/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.2509e-05 - val_accuracy: 0.9870 - val_loss: 0.0761
Epoch 76/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.1796e-05 - val_accuracy: 0.9870 - val_loss: 0.0752
Epoch 77/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.0939e-05 - val_accuracy: 0.9870 - val_loss: 0.0767
Epoch 78/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 2.0132e-05 - val_accuracy: 0.9870 - val_loss: 0.0767
Epoch 79/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.9662e-05 - val_accuracy: 0.9870 - val_loss: 0.0761
Epoch 80/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.8693e-05 - val_accuracy: 0.9870 - val_loss: 0.0788
Epoch 81/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.8043e-05 - val_accuracy: 0.9870 - val_loss: 0.0775
Epoch 82/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.7321e-05 - val_accuracy: 0.9870 - val_loss: 0.0787
Epoch 83/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.6966e-05 - val_accuracy: 0.9870 - val_loss: 0.0777
Epoch 84/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.6258e-05 - val_accuracy: 0.9870 - val_loss: 0.0779
Epoch 85/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.5558e-05 - val_accuracy: 0.9870 - val_loss: 0.0788
Epoch 86/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.4992e-05 - val_accuracy: 0.9870 - val_loss: 0.0789
Epoch 87/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.4510e-05 - val_accuracy: 0.9870 - val_loss: 0.0794
Epoch 88/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.4047e-05 - val_accuracy: 0.9870 - val_loss: 0.0793
Epoch 89/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.3577e-05 - val_accuracy: 0.9870 - val_loss: 0.0799
Epoch 90/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.3080e-05 - val_accuracy: 0.9870 - val_loss: 0.0789
Epoch 91/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.2663e-05 - val_accuracy: 0.9870 - val_loss: 0.0796
Epoch 92/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.2270e-05 - val_accuracy: 0.9870 - val_loss: 0.0814
Epoch 93/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.1789e-05 - val_accuracy: 0.9870 - val_loss: 0.0809
Epoch 94/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.1454e-05 - val_accuracy: 0.9870 - val_loss: 0.0812
Epoch 95/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.1037e-05 - val_accuracy: 0.9870 - val_loss: 0.0806
Epoch 96/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.0679e-05 - val_accuracy: 0.9870 - val_loss: 0.0810
Epoch 97/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.0330e-05 - val_accuracy: 0.9870 - val_loss: 0.0822
Epoch 98/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.0086e-05 - val_accuracy: 0.9870 - val_loss: 0.0806
Epoch 99/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.6789e-06 - val_accuracy: 0.9870 - val_loss: 0.0816
Epoch 100/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.3540e-06 - val_accuracy: 0.9870 - val_loss: 0.0817
Epoch 101/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.0962e-06 - val_accuracy: 0.9870 - val_loss: 0.0820
Epoch 102/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.7810e-06 - val_accuracy: 0.9870 - val_loss: 0.0828
Epoch 103/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.4792e-06 - val_accuracy: 0.9870 - val_loss: 0.0828
Epoch 104/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.2159e-06 - val_accuracy: 0.9870 - val_loss: 0.0837
Epoch 105/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.9732e-06 - val_accuracy: 0.9870 - val_loss: 0.0836
Epoch 106/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.7626e-06 - val_accuracy: 0.9870 - val_loss: 0.0837
Epoch 107/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.4990e-06 - val_accuracy: 0.9870 - val_loss: 0.0832
Epoch 108/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.2663e-06 - val_accuracy: 0.9870 - val_loss: 0.0833
Epoch 109/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 7.0102e-06 - val_accuracy: 0.9870 - val_loss: 0.0838
Epoch 110/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 6.7836e-06 - val_accuracy: 0.9870 - val_loss: 0.0845
Epoch 111/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.5761e-06 - val_accuracy: 0.9870 - val_loss: 0.0851
Epoch 112/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 1.0000 - loss: 6.6502e-06 - val_accuracy: 0.9870 - val_loss: 0.0861
Epoch 113/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 6.3121e-06 - val_accuracy: 0.9870 - val_loss: 0.0850
Epoch 114/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.9645e-06 - val_accuracy: 0.9870 - val_loss: 0.0853
Epoch 115/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.7612e-06 - val_accuracy: 0.9870 - val_loss: 0.0858
Epoch 116/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 5.5953e-06 - val_accuracy: 0.9870 - val_loss: 0.0864
Epoch 117/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.4432e-06 - val_accuracy: 0.9870 - val_loss: 0.0849
Epoch 118/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.2872e-06 - val_accuracy: 0.9870 - val_loss: 0.0863
Epoch 119/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.1095e-06 - val_accuracy: 0.9870 - val_loss: 0.0881
Epoch 120/120
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.9287e-06 - val_accuracy: 0.9870 - val_loss: 0.0874

In [66]:
# 8. Re-evaluate the model
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"\n--- Unified Corrected Model Results ---")
print(f"Final Test Loss:     {test_loss:.4f} (Goal: < 0.1)")
print(f"Final Test Accuracy: {test_accuracy * 100:.2f}% (Goal: > 95%)")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9896 - loss: 0.0816

--- Unified Corrected Model Results ---
Final Test Loss:     0.0816 (Goal: < 0.1)
Final Test Accuracy: 98.96% (Goal: > 95%)

In [67]:
# Save the model using the recommended native Keras format
model.save('tic-tac-toe.keras')
print("Model successfully saved as tic-tac-toe.keras")

Model successfully saved as tic-tac-toe.keras

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [68]:
import numpy as np
import pandas as pd
import tensorflow as tf

# 1. Load your saved model
model = tf.keras.models.load_model('tic-tac-toe.keras')

# 2. Select 5 random indices from the test dataset
# (Assumes X_test and y_test are numpy arrays or dataframes from your split step)
np.random.seed(42)  # For reproducible random choices
random_indices = np.random.choice(len(X_test), size=5, replace=False)

# 3. Extract the random samples and their true labels safely
if isinstance(X_test, pd.DataFrame):
    samples = X_test.iloc[random_indices]
else:
    samples = X_test[random_indices]

# Force index matching by using .iloc or converting pandas Series to numpy array
if isinstance(y_test, (pd.Series, pd.DataFrame)):
    true_labels = y_test.iloc[random_indices].values
else:
    true_labels = y_test[random_indices]


# 4. Make predictions
# The model outputs probabilities for each class (e.g., [0.15, 0.85]) due to softmax
raw_predictions = model.predict(samples)

# Use argmax to pick the class index with the highest probability (0 or 1)
predicted_classes = np.argmax(raw_predictions, axis=1)

# 5. Display and compare the results
print("\n--- Prediction Results ---")
for i in range(len(random_indices)):
    print(f"Sample {i+1}:")
    print(f"  Predicted Class: {predicted_classes[i]}")
    print(f"  Actual Class:    {true_labels[i]}")

    # Check if the model got it right
    if predicted_classes[i] == true_labels[i]:
        print("  Result:          ✅ Correct!")
    else:
        print("  Result:          ❌ Incorrect")
    print("-" * 25)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 404ms/step

--- Prediction Results ---
Sample 1:
  Predicted Class: 0
  Actual Class:    0
  Result:          ✅ Correct!
-------------------------
Sample 2:
  Predicted Class: 1
  Actual Class:    1
  Result:          ✅ Correct!
-------------------------
Sample 3:
  Predicted Class: 1
  Actual Class:    1
  Result:          ✅ Correct!
-------------------------
Sample 4:
  Predicted Class: 1
  Actual Class:    1
  Result:          ✅ Correct!
-------------------------
Sample 5:
  Predicted Class: 0
  Actual Class:    0
  Result:          ✅ Correct!
-------------------------

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [71]:
import tensorflow as tf

# 1. Architecture with Dropout to stabilize and minimize final loss
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.1))  # Prevents final-epoch overfitting fluctuations
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(2, activation='softmax'))

# 2. Optimized compilation
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# 3. Train for 150 epochs to guarantee the loss drops below 0.1
history = model.fit(
    X_train,
    y_train,
    epochs=150,
    batch_size=16,
    validation_split=0.1,
    verbose=1
)

# 4. Evaluate the stabilized network
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"\n--- Final Stabilized Model Results ---")
print(f"Final Test Loss:     {test_loss:.4f} (Goal: < 0.1)")
print(f"Final Test Accuracy: {test_accuracy * 100:.2f}% (Goal: > 95%)")

Epoch 1/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.6415 - loss: 0.6294 - val_accuracy: 0.7792 - val_loss: 0.5276
Epoch 2/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7199 - loss: 0.5474 - val_accuracy: 0.8052 - val_loss: 0.4705
Epoch 3/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7460 - loss: 0.5014 - val_accuracy: 0.7922 - val_loss: 0.4504
Epoch 4/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7794 - loss: 0.4561 - val_accuracy: 0.8312 - val_loss: 0.4081
Epoch 5/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8186 - loss: 0.3951 - val_accuracy: 0.8571 - val_loss: 0.3673
Epoch 6/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8505 - loss: 0.3515 - val_accuracy: 0.8831 - val_loss: 0.3076
Epoch 7/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9042 - loss: 0.2687 - val_accuracy: 0.8961 - val_loss: 0.2582
Epoch 8/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9347 - loss: 0.2191 - val_accuracy: 0.9091 - val_loss: 0.2226
Epoch 9/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9478 - loss: 0.1651 - val_accuracy: 0.9351 - val_loss: 0.1873
Epoch 10/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9623 - loss: 0.1328 - val_accuracy: 0.9610 - val_loss: 0.1545
Epoch 11/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9637 - loss: 0.1203 - val_accuracy: 0.9610 - val_loss: 0.1437
Epoch 12/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9782 - loss: 0.0864 - val_accuracy: 0.9351 - val_loss: 0.1490
Epoch 13/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9739 - loss: 0.0789 - val_accuracy: 0.9870 - val_loss: 0.0865
Epoch 14/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9768 - loss: 0.0718 - val_accuracy: 0.9610 - val_loss: 0.1459
Epoch 15/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9869 - loss: 0.0590 - val_accuracy: 0.9870 - val_loss: 0.1136
Epoch 16/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9869 - loss: 0.0469 - val_accuracy: 0.9740 - val_loss: 0.1157
Epoch 17/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9840 - loss: 0.0495 - val_accuracy: 0.9351 - val_loss: 0.1143
Epoch 18/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9898 - loss: 0.0432 - val_accuracy: 0.9870 - val_loss: 0.0783
Epoch 19/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9811 - loss: 0.0415 - val_accuracy: 0.9740 - val_loss: 0.0656
Epoch 20/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9913 - loss: 0.0327 - val_accuracy: 0.9870 - val_loss: 0.1108
Epoch 21/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9898 - loss: 0.0328 - val_accuracy: 0.9740 - val_loss: 0.0782
Epoch 22/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9927 - loss: 0.0262 - val_accuracy: 0.9740 - val_loss: 0.0769
Epoch 23/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9956 - loss: 0.0246 - val_accuracy: 0.9740 - val_loss: 0.0697
Epoch 24/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9927 - loss: 0.0216 - val_accuracy: 0.9870 - val_loss: 0.0457
Epoch 25/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0129 - val_accuracy: 0.9740 - val_loss: 0.0520
Epoch 26/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9971 - loss: 0.0139 - val_accuracy: 0.9870 - val_loss: 0.0734
Epoch 27/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9956 - loss: 0.0131 - val_accuracy: 0.9870 - val_loss: 0.0864
Epoch 28/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9942 - loss: 0.0207 - val_accuracy: 0.9740 - val_loss: 0.1048
Epoch 29/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9942 - loss: 0.0200 - val_accuracy: 0.9870 - val_loss: 0.0893
Epoch 30/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9942 - loss: 0.0185 - val_accuracy: 0.9610 - val_loss: 0.1406
Epoch 31/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0129 - val_accuracy: 0.9740 - val_loss: 0.0965
Epoch 32/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9956 - loss: 0.0165 - val_accuracy: 0.9870 - val_loss: 0.0865
Epoch 33/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0084 - val_accuracy: 0.9740 - val_loss: 0.1075
Epoch 34/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0116 - val_accuracy: 0.9870 - val_loss: 0.0893
Epoch 35/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9913 - loss: 0.0227 - val_accuracy: 0.9740 - val_loss: 0.0617
Epoch 36/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0143 - val_accuracy: 0.9870 - val_loss: 0.0949
Epoch 37/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9956 - loss: 0.0167 - val_accuracy: 0.9870 - val_loss: 0.0596
Epoch 38/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0062 - val_accuracy: 0.9870 - val_loss: 0.0211
Epoch 39/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0081 - val_accuracy: 0.9740 - val_loss: 0.0687
Epoch 40/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.9870 - val_loss: 0.0739
Epoch 41/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.9870 - val_loss: 0.0600
Epoch 42/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9956 - loss: 0.0092 - val_accuracy: 0.9740 - val_loss: 0.0574
Epoch 43/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0110 - val_accuracy: 0.9870 - val_loss: 0.0876
Epoch 44/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.9740 - val_loss: 0.0985
Epoch 45/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9956 - loss: 0.0072 - val_accuracy: 0.9740 - val_loss: 0.1013
Epoch 46/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.9740 - val_loss: 0.0582
Epoch 47/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0076 - val_accuracy: 0.9870 - val_loss: 0.0861
Epoch 48/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0054 - val_accuracy: 0.9740 - val_loss: 0.1167
Epoch 49/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.9870 - val_loss: 0.0832
Epoch 50/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0081 - val_accuracy: 0.9610 - val_loss: 0.0723
Epoch 51/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.9870 - val_loss: 0.0836
Epoch 52/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0100 - val_accuracy: 0.9740 - val_loss: 0.1249
Epoch 53/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9927 - loss: 0.0236 - val_accuracy: 0.9870 - val_loss: 0.1066
Epoch 54/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0091 - val_accuracy: 0.9870 - val_loss: 0.0708
Epoch 55/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0074 - val_accuracy: 0.9870 - val_loss: 0.0803
Epoch 56/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.9740 - val_loss: 0.0427
Epoch 57/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0079 - val_accuracy: 0.9740 - val_loss: 0.0998
Epoch 58/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0062 - val_accuracy: 0.9870 - val_loss: 0.0706
Epoch 59/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9956 - loss: 0.0128 - val_accuracy: 0.9870 - val_loss: 0.0580
Epoch 60/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0028 - val_accuracy: 0.9740 - val_loss: 0.0764
Epoch 61/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.9870 - val_loss: 0.0982
Epoch 62/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0076 - val_accuracy: 0.9870 - val_loss: 0.0686
Epoch 63/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0078 - val_accuracy: 0.9481 - val_loss: 0.1522
Epoch 64/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9956 - loss: 0.0078 - val_accuracy: 0.9740 - val_loss: 0.1281
Epoch 65/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0030 - val_accuracy: 0.9870 - val_loss: 0.0934
Epoch 66/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0045 - val_accuracy: 0.9870 - val_loss: 0.0919
Epoch 67/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0044 - val_accuracy: 0.9870 - val_loss: 0.0910
Epoch 68/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0060 - val_accuracy: 0.9740 - val_loss: 0.0902
Epoch 69/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0049 - val_accuracy: 0.9870 - val_loss: 0.0490
Epoch 70/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9971 - loss: 0.0086 - val_accuracy: 0.9870 - val_loss: 0.1037
Epoch 71/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9898 - loss: 0.0288 - val_accuracy: 0.9870 - val_loss: 0.0697
Epoch 72/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.9870 - val_loss: 0.0719
Epoch 73/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0099 - val_accuracy: 0.9870 - val_loss: 0.0796
Epoch 74/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0074 - val_accuracy: 0.9870 - val_loss: 0.0261
Epoch 75/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0057 - val_accuracy: 0.9870 - val_loss: 0.0606
Epoch 76/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0088 - val_accuracy: 0.9870 - val_loss: 0.0636
Epoch 77/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9870 - val_loss: 0.0732
Epoch 78/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0037 - val_accuracy: 0.9870 - val_loss: 0.0817
Epoch 79/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9870 - val_loss: 0.0874
Epoch 80/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.9870 - val_loss: 0.0848
Epoch 81/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9956 - loss: 0.0077 - val_accuracy: 0.9610 - val_loss: 0.1316
Epoch 82/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9942 - loss: 0.0099 - val_accuracy: 0.9870 - val_loss: 0.0884
Epoch 83/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9870 - val_loss: 0.0834
Epoch 84/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9870 - val_loss: 0.0664
Epoch 85/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9870 - val_loss: 0.0637
Epoch 86/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9971 - loss: 0.0038 - val_accuracy: 0.9870 - val_loss: 0.1203
Epoch 87/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9985 - loss: 0.0097 - val_accuracy: 0.9870 - val_loss: 0.0479
Epoch 88/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9870 - val_loss: 0.0930
Epoch 89/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9870 - val_loss: 0.0548
Epoch 90/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9985 - loss: 0.0050 - val_accuracy: 0.9740 - val_loss: 0.1061
Epoch 91/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.9870 - val_loss: 0.0860
Epoch 92/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.9870 - val_loss: 0.0876
Epoch 93/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0034 - val_accuracy: 0.9870 - val_loss: 0.0580
Epoch 94/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.1635e-04 - val_accuracy: 0.9870 - val_loss: 0.0556
Epoch 95/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.2648e-04 - val_accuracy: 0.9870 - val_loss: 0.0369
Epoch 96/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.7652e-04 - val_accuracy: 0.9870 - val_loss: 0.0381
Epoch 97/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.3079e-04 - val_accuracy: 0.9870 - val_loss: 0.0299
Epoch 98/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9870 - val_loss: 0.0387
Epoch 99/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9927 - loss: 0.0147 - val_accuracy: 0.9870 - val_loss: 0.1495
Epoch 100/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9985 - loss: 0.0119 - val_accuracy: 0.9870 - val_loss: 0.1140
Epoch 101/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.8161e-04 - val_accuracy: 0.9870 - val_loss: 0.1154
Epoch 102/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.5374e-04 - val_accuracy: 0.9870 - val_loss: 0.1072
Epoch 103/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.6114e-04 - val_accuracy: 0.9870 - val_loss: 0.1184
Epoch 104/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0112 - val_accuracy: 0.9870 - val_loss: 0.0859
Epoch 105/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0029 - val_accuracy: 0.9870 - val_loss: 0.0411
Epoch 106/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0123 - val_accuracy: 0.9481 - val_loss: 0.1331
Epoch 107/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9869 - loss: 0.0431 - val_accuracy: 0.9870 - val_loss: 0.1151
Epoch 108/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9927 - loss: 0.0169 - val_accuracy: 0.9870 - val_loss: 0.0734
Epoch 109/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9811 - loss: 0.0497 - val_accuracy: 0.9870 - val_loss: 0.0383
Epoch 110/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9913 - loss: 0.0278 - val_accuracy: 0.9870 - val_loss: 0.0470
Epoch 111/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0103 - val_accuracy: 0.9870 - val_loss: 0.0736
Epoch 112/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9927 - loss: 0.0158 - val_accuracy: 0.9870 - val_loss: 0.1033
Epoch 113/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.9870 - val_loss: 0.0551
Epoch 114/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9740 - val_loss: 0.0712
Epoch 115/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.0468e-04 - val_accuracy: 0.9870 - val_loss: 0.0733
Epoch 116/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.3704e-04 - val_accuracy: 0.9870 - val_loss: 0.0595
Epoch 117/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.5969e-04 - val_accuracy: 0.9870 - val_loss: 0.0642
Epoch 118/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.2737e-04 - val_accuracy: 0.9870 - val_loss: 0.0648
Epoch 119/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.5692e-04 - val_accuracy: 0.9870 - val_loss: 0.0664
Epoch 120/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0061 - val_accuracy: 0.9870 - val_loss: 0.0993
Epoch 121/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0061 - val_accuracy: 0.9870 - val_loss: 0.0682
Epoch 122/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.7087e-04 - val_accuracy: 0.9870 - val_loss: 0.0743
Epoch 123/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9971 - loss: 0.0056 - val_accuracy: 0.9870 - val_loss: 0.0667
Epoch 124/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9870 - val_loss: 0.0994
Epoch 125/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.9870 - val_loss: 0.0564
Epoch 126/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0049 - val_accuracy: 0.9870 - val_loss: 0.0525
Epoch 127/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0046 - val_accuracy: 0.9870 - val_loss: 0.0485
Epoch 128/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 6.0457e-04 - val_accuracy: 0.9870 - val_loss: 0.0471
Epoch 129/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 6.9894e-04 - val_accuracy: 0.9870 - val_loss: 0.0661
Epoch 130/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0034 - val_accuracy: 0.9870 - val_loss: 0.0260
Epoch 131/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9870 - val_loss: 0.0453
Epoch 132/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0029 - val_accuracy: 0.9870 - val_loss: 0.0578
Epoch 133/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0037 - val_accuracy: 0.9870 - val_loss: 0.0793
Epoch 134/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0030 - val_accuracy: 0.9870 - val_loss: 0.0721
Epoch 135/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.9870 - val_loss: 0.0999
Epoch 136/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9971 - loss: 0.0063 - val_accuracy: 0.9870 - val_loss: 0.0830
Epoch 137/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.1798e-04 - val_accuracy: 0.9870 - val_loss: 0.0769
Epoch 138/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.4731e-04 - val_accuracy: 0.9870 - val_loss: 0.0882
Epoch 139/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 9.1795e-04 - val_accuracy: 0.9870 - val_loss: 0.0725
Epoch 140/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.9870 - val_loss: 0.0662
Epoch 141/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9870 - val_loss: 0.0533
Epoch 142/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9942 - loss: 0.0170 - val_accuracy: 0.9870 - val_loss: 0.0345
Epoch 143/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.9870 - val_loss: 0.0200
Epoch 144/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9942 - loss: 0.0144 - val_accuracy: 0.9870 - val_loss: 0.1024
Epoch 145/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0043 - val_accuracy: 0.9870 - val_loss: 0.0291
Epoch 146/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9870 - val_loss: 0.0532
Epoch 147/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.5796e-04 - val_accuracy: 0.9870 - val_loss: 0.0657
Epoch 148/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.7699e-04 - val_accuracy: 0.9870 - val_loss: 0.0611
Epoch 149/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.3387e-04 - val_accuracy: 0.9870 - val_loss: 0.0802
Epoch 150/150
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.6736e-04 - val_accuracy: 0.9870 - val_loss: 0.0634
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9792 - loss: 0.0449

--- Final Stabilized Model Results ---
Final Test Loss:     0.0449 (Goal: < 0.1)
Final Test Accuracy: 97.92% (Goal: > 95%)

**Which approach(es) did you find helpful to improve your model performance?**

In [74]:
# Save your optimized model to the native Keras format
model.save('tic-tac-toe_optimized.keras')
print("Optimized model successfully saved as 'tic-tac-toe_optimized.keras'!")

Optimized model successfully saved as 'tic-tac-toe_optimized.keras'!

In [73]:
# ==============================================================================
# OPTIMIZATION SUMMARY & MODEL PERFORMANCE NOTES:
#
# 1. Spatial Feature Mapping: Replaced default LabelEncoder with a custom
#    map ('b':0, 'o':-1, 'x':1). This eliminated unintended numerical hierarchies.
# 2. Capacity Adjustment: Expanded hidden layout to 128 -> 64 -> 32 nodes
#    to successfully capture intersecting horizontal, vertical, and diagonal lines.
# 3. Regularization: Added a 10% Dropout layer and tracked for 150 epochs
#    to curb late-stage overfitting fluctuations on small tabular structures.
#
# Target Benchmarks Met: Final Test Loss: 0.0449 | Final Test Accuracy: 97.92%
# ==============================================================================